
package soap.processcentricservices;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ProcessCentricServices", targetNamespace = "http://processcentricservices.soap/", wsdlLocation = "http://localhost:451/ws/processcentricservice?wsdl")
public class ProcessCentricServices_Service
    extends Service
{

    private final static URL PROCESSCENTRICSERVICES_WSDL_LOCATION;
    private final static WebServiceException PROCESSCENTRICSERVICES_EXCEPTION;
    private final static QName PROCESSCENTRICSERVICES_QNAME = new QName("http://processcentricservices.soap/", "ProcessCentricServices");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:451/ws/processcentricservice?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PROCESSCENTRICSERVICES_WSDL_LOCATION = url;
        PROCESSCENTRICSERVICES_EXCEPTION = e;
    }

    public ProcessCentricServices_Service() {
        super(__getWsdlLocation(), PROCESSCENTRICSERVICES_QNAME);
    }

    public ProcessCentricServices_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), PROCESSCENTRICSERVICES_QNAME, features);
    }

    public ProcessCentricServices_Service(URL wsdlLocation) {
        super(wsdlLocation, PROCESSCENTRICSERVICES_QNAME);
    }

    public ProcessCentricServices_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PROCESSCENTRICSERVICES_QNAME, features);
    }

    public ProcessCentricServices_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProcessCentricServices_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ProcessCentricServices
     */
    @WebEndpoint(name = "ProcessCentricServicesImplementationPort")
    public ProcessCentricServices getProcessCentricServicesImplementationPort() {
        return super.getPort(new QName("http://processcentricservices.soap/", "ProcessCentricServicesImplementationPort"), ProcessCentricServices.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProcessCentricServices
     */
    @WebEndpoint(name = "ProcessCentricServicesImplementationPort")
    public ProcessCentricServices getProcessCentricServicesImplementationPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://processcentricservices.soap/", "ProcessCentricServicesImplementationPort"), ProcessCentricServices.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PROCESSCENTRICSERVICES_EXCEPTION!= null) {
            throw PROCESSCENTRICSERVICES_EXCEPTION;
        }
        return PROCESSCENTRICSERVICES_WSDL_LOCATION;
    }

}
