
package soap.processcentricservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ProcessCentricServices", targetNamespace = "http://processcentricservices.soap/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProcessCentricServices {


    /**
     * 
     * @param userdata
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "register", targetNamespace = "")
    @RequestWrapper(localName = "register", targetNamespace = "http://processcentricservices.soap/", className = "soap.processcentricservices.Register")
    @ResponseWrapper(localName = "registerResponse", targetNamespace = "http://processcentricservices.soap/", className = "soap.processcentricservices.RegisterResponse")
    @Action(input = "http://processcentricservices.soap/ProcessCentricServices/registerRequest", output = "http://processcentricservices.soap/ProcessCentricServices/registerResponse")
    public int register(
        @WebParam(name = "userdata", targetNamespace = "")
        String userdata);

    /**
     * 
     * @param userdata
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "login", targetNamespace = "")
    @RequestWrapper(localName = "login", targetNamespace = "http://processcentricservices.soap/", className = "soap.processcentricservices.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://processcentricservices.soap/", className = "soap.processcentricservices.LoginResponse")
    @Action(input = "http://processcentricservices.soap/ProcessCentricServices/loginRequest", output = "http://processcentricservices.soap/ProcessCentricServices/loginResponse")
    public int login(
        @WebParam(name = "userdata", targetNamespace = "")
        String userdata);

    /**
     * 
     * @param id
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "getMeasures", targetNamespace = "")
    @RequestWrapper(localName = "getMeasures", targetNamespace = "http://processcentricservices.soap/", className = "soap.processcentricservices.GetMeasures")
    @ResponseWrapper(localName = "getMeasuresResponse", targetNamespace = "http://processcentricservices.soap/", className = "soap.processcentricservices.GetMeasuresResponse")
    @Action(input = "http://processcentricservices.soap/ProcessCentricServices/getMeasuresRequest", output = "http://processcentricservices.soap/ProcessCentricServices/getMeasuresResponse")
    public String getMeasures(
        @WebParam(name = "id", targetNamespace = "")
        int id);

    /**
     * 
     * @param id
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "goals", targetNamespace = "")
    @RequestWrapper(localName = "getGoals", targetNamespace = "http://processcentricservices.soap/", className = "soap.processcentricservices.GetGoals")
    @ResponseWrapper(localName = "getGoalsResponse", targetNamespace = "http://processcentricservices.soap/", className = "soap.processcentricservices.GetGoalsResponse")
    @Action(input = "http://processcentricservices.soap/ProcessCentricServices/getGoalsRequest", output = "http://processcentricservices.soap/ProcessCentricServices/getGoalsResponse")
    public String getGoals(
        @WebParam(name = "id", targetNamespace = "")
        int id);

    /**
     * 
     * @param id
     * @param arg1
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "registerGoal", targetNamespace = "")
    @RequestWrapper(localName = "registerGoal", targetNamespace = "http://processcentricservices.soap/", className = "soap.processcentricservices.RegisterGoal")
    @ResponseWrapper(localName = "registerGoalResponse", targetNamespace = "http://processcentricservices.soap/", className = "soap.processcentricservices.RegisterGoalResponse")
    @Action(input = "http://processcentricservices.soap/ProcessCentricServices/registerGoalRequest", output = "http://processcentricservices.soap/ProcessCentricServices/registerGoalResponse")
    public String registerGoal(
        @WebParam(name = "id", targetNamespace = "")
        int id,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "getQuote", targetNamespace = "")
    @RequestWrapper(localName = "getQuote", targetNamespace = "http://processcentricservices.soap/", className = "soap.processcentricservices.GetQuote")
    @ResponseWrapper(localName = "getQuoteResponse", targetNamespace = "http://processcentricservices.soap/", className = "soap.processcentricservices.GetQuoteResponse")
    @Action(input = "http://processcentricservices.soap/ProcessCentricServices/getQuoteRequest", output = "http://processcentricservices.soap/ProcessCentricServices/getQuoteResponse")
    public String getQuote();

    /**
     * 
     * @param id
     * @param arg1
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "registerMeasurment", targetNamespace = "")
    @RequestWrapper(localName = "registerMeasurment", targetNamespace = "http://processcentricservices.soap/", className = "soap.processcentricservices.RegisterMeasurment")
    @ResponseWrapper(localName = "registerMeasurmentResponse", targetNamespace = "http://processcentricservices.soap/", className = "soap.processcentricservices.RegisterMeasurmentResponse")
    @Action(input = "http://processcentricservices.soap/ProcessCentricServices/registerMeasurmentRequest", output = "http://processcentricservices.soap/ProcessCentricServices/registerMeasurmentResponse")
    public String registerMeasurment(
        @WebParam(name = "id", targetNamespace = "")
        int id,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param id
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "getProgressInfo", targetNamespace = "")
    @RequestWrapper(localName = "getProgressInfo", targetNamespace = "http://processcentricservices.soap/", className = "soap.processcentricservices.GetProgressInfo")
    @ResponseWrapper(localName = "getProgressInfoResponse", targetNamespace = "http://processcentricservices.soap/", className = "soap.processcentricservices.GetProgressInfoResponse")
    @Action(input = "http://processcentricservices.soap/ProcessCentricServices/getProgressInfoRequest", output = "http://processcentricservices.soap/ProcessCentricServices/getProgressInfoResponse")
    public String getProgressInfo(
        @WebParam(name = "id", targetNamespace = "")
        int id);

    /**
     * 
     * @param measurmentDescription
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "addNewMeasurmentType", targetNamespace = "")
    @RequestWrapper(localName = "addNewMeasurmentType", targetNamespace = "http://processcentricservices.soap/", className = "soap.processcentricservices.AddNewMeasurmentType")
    @ResponseWrapper(localName = "addNewMeasurmentTypeResponse", targetNamespace = "http://processcentricservices.soap/", className = "soap.processcentricservices.AddNewMeasurmentTypeResponse")
    @Action(input = "http://processcentricservices.soap/ProcessCentricServices/addNewMeasurmentTypeRequest", output = "http://processcentricservices.soap/ProcessCentricServices/addNewMeasurmentTypeResponse")
    public int addNewMeasurmentType(
        @WebParam(name = "measurmentDescription", targetNamespace = "")
        String measurmentDescription);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "getMeasurmentTypes", targetNamespace = "")
    @RequestWrapper(localName = "getMeasurmentTypes", targetNamespace = "http://processcentricservices.soap/", className = "soap.processcentricservices.GetMeasurmentTypes")
    @ResponseWrapper(localName = "getMeasurmentTypesResponse", targetNamespace = "http://processcentricservices.soap/", className = "soap.processcentricservices.GetMeasurmentTypesResponse")
    @Action(input = "http://processcentricservices.soap/ProcessCentricServices/getMeasurmentTypesRequest", output = "http://processcentricservices.soap/ProcessCentricServices/getMeasurmentTypesResponse")
    public String getMeasurmentTypes();

}
